/*
 * SwaggerPetstore.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerPetstore.PCL;
using SwaggerPetstore.PCL.Utilities;

namespace SwaggerPetstore.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum Status7Enum
    {
        AVAILABLE, //TODO: Write general description for this method
        PENDING, //TODO: Write general description for this method
        SOLD, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type Status7Enum
    /// </summary>
    public static class Status7EnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "available", "pending", "sold" };

        /// <summary>
        /// Converts a Status7Enum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The Status7Enum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(Status7Enum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case Status7Enum.AVAILABLE:
                case Status7Enum.PENDING:
                case Status7Enum.SOLD:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of Status7Enum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of Status7Enum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<Status7Enum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into Status7Enum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed Status7Enum value</returns>
        public static Status7Enum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type Status7Enum", value));

            return (Status7Enum) index;
        }
    }
} 